#!/usr/bin/env php
<?php

(function () {
    $paths = [
        __DIR__ . '/vendor/autoload.php',
        __DIR__ . '/../../vendor/autoload.php',
        getcwd() . '/vendor/autoload.php',
    ];

    foreach ($paths as $path) {
        if (file_exists($path)) {
            require $path;
            break;
        }
    }

    $app = new Helix\Console\Application();
    $app->run();
})();
